spring:
  datasource:
    url: jdbc:mysql://database-1.clqwo2gs83ac.ap-northeast-2.rds.amazonaws.com:3306/whowantit
    username: ${MYSQL_USER}
    password: ${MYSQL_PW}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl # 카멜 -> 스네이크 표기법 변환
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000
spring-doc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: method

cloud:
  aws:
    s3:
      bucket: whowantitbucket
      path:
        picture : picture
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_ACCESS_KEY}